/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dog_patron.gltf --transform --types
Author: DeadLink (https://sketchfab.com/hell3879)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dog-patron-hero-of-ukraine-update-68b33380be2741c69e5b195ae3f8fee1
Title: Dog "PATRON" Hero of Ukraine (UPDATE)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
  }
  materials: {
    PM3D_Cube3D_2_lambert: THREE.MeshStandardMaterial
    PATRON1_lambert: THREE.MeshStandardMaterial
    PATRON_lambert: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/dog_patron-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.PM3D_Cube3D_2_lambert} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.PATRON1_lambert} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.PATRON1_lambert} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.PATRON1_lambert} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.PATRON1_lambert} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.PATRON1_lambert} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.PATRON_lambert} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dog_patron-transformed.glb')
