/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pickle_rick.gltf --transform --types
Author: mister dude (https://sketchfab.com/misterdude)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pickle-rick-rat-suit-c3c71a9c380c4b6298d0546db68a733c
Title: Pickle Rick (Rat Suit)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Object_11: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Limbs: THREE.MeshStandardMaterial
    Suit: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/pickle_rick-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Body} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Limbs} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials.Suit}
          skeleton={nodes.Object_11.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pickle_rick-transformed.glb')
