/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cucumber_rick.gltf --transform --types
Author: hellfa (https://sketchfab.com/hellfa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retopo-rick-f673ab6508064e438f96b70502646949
Title: Retopo Rick
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
  }
  materials: {
    eye_lp: THREE.MeshStandardMaterial
    buziaa: THREE.MeshStandardMaterial
    ogorek: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cucumber_rick-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.eye_lp} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.buziaa} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.ogorek} />
      </group>
    </group>
  )
}

useGLTF.preload('/cucumber_rick-transformed.glb')
