/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 himars.gltf --transform --types
Author: Pipin (https://sketchfab.com/artemfesenko7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/himars-b385b52afd0e426ab93b17eef8ecfe4f
Title: Himars
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Default_Metal_Decorative_Patina_0: THREE.Mesh
    Default_Metal_Decorative_Patina_0_1: THREE.Mesh
    Default_Metal_Decorative_Patina_0_2: THREE.Mesh
    Default_Metal_Decorative_Patina_0_3: THREE.Mesh
    Default_Metal_Decorative_Patina_0_4: THREE.Mesh
    Default_Metal_Decorative_Patina_0_5: THREE.Mesh
    Default_Metal_Decorative_Patina_0_6: THREE.Mesh
    Default_Metal_Decorative_Patina_0_7: THREE.Mesh
    Default_Metal_Decorative_Patina_0_8: THREE.Mesh
    Default_Metal_Decorative_Patina_0_9: THREE.Mesh
    Default_Metal_Decorative_Patina_0_10: THREE.Mesh
    Default_Metal_Decorative_Patina_0_11: THREE.Mesh
    Default_Metal_Decorative_Patina_0_12: THREE.Mesh
    Default_Metal_Decorative_Patina_0_13: THREE.Mesh
    Default_Metal_Decorative_Patina_0_14: THREE.Mesh
    Default_Metal_Decorative_Patina_0_15: THREE.Mesh
    Default_Metal_Decorative_Patina_0_16: THREE.Mesh
    Default_Metal_Decorative_Patina_0_17: THREE.Mesh
    Default_Glass_Clear_Distorted_0: THREE.Mesh
    Default_Rubber_Rough_Dirty_0: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_1: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_2: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_3: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_4: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_5: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_6: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_7: THREE.Mesh
    Default_Rubber_Rough_Dirty_0_8: THREE.Mesh
    Default_Iron_Rough_0: THREE.Mesh
    Default_Iron_Rough_0_1: THREE.Mesh
    Default_Iron_Rough_0_2: THREE.Mesh
    Default_1_Light_0: THREE.Mesh
  }
  materials: {
    Metal_Decorative_Patina: THREE.MeshStandardMaterial
    Glass_Clear_Distorted: THREE.MeshStandardMaterial
    Rubber_Rough_Dirty: THREE.MeshStandardMaterial
    Iron_Rough: THREE.MeshStandardMaterial
    Light: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/himars-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.9}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_1.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_2.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_3.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_4.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_5.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_6.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_7.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_8.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_9.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_10.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_11.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_12.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_13.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_14.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_15.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_16.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh
            geometry={nodes.Default_Metal_Decorative_Patina_0_17.geometry}
            material={materials.Metal_Decorative_Patina}
          />
          <mesh geometry={nodes.Default_Glass_Clear_Distorted_0.geometry} material={materials.Glass_Clear_Distorted} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_1.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_2.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_3.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_4.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_5.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_6.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_7.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Rubber_Rough_Dirty_0_8.geometry} material={materials.Rubber_Rough_Dirty} />
          <mesh geometry={nodes.Default_Iron_Rough_0.geometry} material={materials.Iron_Rough} />
          <mesh geometry={nodes.Default_Iron_Rough_0_1.geometry} material={materials.Iron_Rough} />
          <mesh geometry={nodes.Default_Iron_Rough_0_2.geometry} material={materials.Iron_Rough} />
          <mesh geometry={nodes.Default_1_Light_0.geometry} material={materials.Light} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/himars-transformed.glb')
