/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mr_meeseks.gltf --transform --types
Author: ElSalawwy (https://sketchfab.com/andressalazar264)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mr-meeseks-356fca081a514508bf8d344ec1515d3f
Title: Mr Meeseks
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cuerpo_lambert6_0: THREE.Mesh
    Cuerpo_lambert3_0: THREE.Mesh
    Cuerpo_lambert4_0: THREE.Mesh
    Cuerpo_lambert2_0: THREE.Mesh
    Cuerpo_lambert5_0: THREE.Mesh
  }
  materials: {
    lambert6: THREE.MeshStandardMaterial
    lambert3: THREE.MeshStandardMaterial
    lambert4: THREE.MeshStandardMaterial
    lambert2: THREE.MeshStandardMaterial
    lambert5: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mr_meeseks-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[8.86, 0, -2.55]}>
        <mesh  geometry={nodes.Cuerpo_lambert6_0.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.Cuerpo_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.Cuerpo_lambert4_0.geometry} material={materials.lambert4} />
        <mesh geometry={nodes.Cuerpo_lambert2_0.geometry} material={materials.lambert2} />
        <mesh geometry={nodes.Cuerpo_lambert5_0.geometry} material={materials.lambert5} />
      </group>
    </group>
  )
}

useGLTF.preload('/mr_meeseks-transformed.glb')
