/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 putin_huilo.gltf --transform --types
Author: Idmental (https://sketchfab.com/idmental.id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/putin-huilo--missle-decc9caab81846e799b88385839593e9
Title: Putin Huilo _Missle
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import { Group } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    missle_missle_0: THREE.Mesh
  }
  materials: {
    missle: THREE.MeshPhysicalMaterial
  }
}

export default function Model() {
  const { scene } = useGLTF('/putin_huilo-transformed.glb')

  return <primitive scale={5} object={scene} />
}

// useGLTF.preload('/putin_huilo-transformed.glb')
